//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activado.
        /// </summary>
        internal static string activated {
            get {
                return ResourceManager.GetString("activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir.
        /// </summary>
        internal static string addBtn {
            get {
                return ResourceManager.GetString("addBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir evento.
        /// </summary>
        internal static string addEventBtn {
            get {
                return ResourceManager.GetString("addEventBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta eliminada correctamente.
        /// </summary>
        internal static string alertDelete {
            get {
                return ResourceManager.GetString("alertDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al almacenar la alerta.
        /// </summary>
        internal static string alertError {
            get {
                return ResourceManager.GetString("alertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta creada correctamente.
        /// </summary>
        internal static string alertOK {
            get {
                return ResourceManager.GetString("alertOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertas.
        /// </summary>
        internal static string alerts {
            get {
                return ResourceManager.GetString("alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un tipo de alerta.
        /// </summary>
        internal static string alertSelect {
            get {
                return ResourceManager.GetString("alertSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una alerta asociada a esa zona. Elimínela antes de crear una nueva.
        /// </summary>
        internal static string alertZone {
            get {
                return ResourceManager.GetString("alertZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir minimizar.
        /// </summary>
        internal static string allowToMinimize {
            get {
                return ResourceManager.GetString("allowToMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apllicar.
        /// </summary>
        internal static string applyBtn {
            get {
                return ResourceManager.GetString("applyBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistidos.
        /// </summary>
        internal static string asists {
            get {
                return ResourceManager.GetString("asists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta de batería.
        /// </summary>
        internal static string batteryLevelAlarm {
            get {
                return ResourceManager.GetString("batteryLevelAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición aproximada.
        /// </summary>
        internal static string cellid {
            get {
                return ResourceManager.GetString("cellid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        internal static string clearBtn {
            get {
                return ResourceManager.GetString("clearBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string configuration {
            get {
                return ResourceManager.GetString("configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRÚA.
        /// </summary>
        internal static string crane {
            get {
                return ResourceManager.GetString("crane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha creado el evento correctamente.
        /// </summary>
        internal static string createOkEvent {
            get {
                return ResourceManager.GetString("createOkEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Asistido.
        /// </summary>
        internal static string dataAssisted {
            get {
                return ResourceManager.GetString("dataAssisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Nac..
        /// </summary>
        internal static string dateBorn {
            get {
                return ResourceManager.GetString("dateBorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string deleteBtn {
            get {
                return ResourceManager.GetString("deleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de emergencia.
        /// </summary>
        internal static string emergencyNumber {
            get {
                return ResourceManager.GetString("emergencyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creando evento.
        /// </summary>
        internal static string errorCreateEvent {
            get {
                return ResourceManager.GetString("errorCreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error al guardar los datos.
        /// </summary>
        internal static string errorData {
            get {
                return ResourceManager.GetString("errorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha producido un error al eliminar el evento.
        /// </summary>
        internal static string errorDeleteEvent {
            get {
                return ResourceManager.GetString("errorDeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nuevo evento.
        /// </summary>
        internal static string eventCreate {
            get {
                return ResourceManager.GetString("eventCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos planificados.
        /// </summary>
        internal static string eventPlanification {
            get {
                return ResourceManager.GetString("eventPlanification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existen eventos asociados a la zona.
        /// </summary>
        internal static string existsEventsInZone {
            get {
                return ResourceManager.GetString("existsEventsInZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño máximo de la imagen: 60x90 píxeles.
        /// </summary>
        internal static string filterImage {
            get {
                return ResourceManager.GetString("filterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string findBtn {
            get {
                return ResourceManager.GetString("findBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertas generales.
        /// </summary>
        internal static string generalAlerts {
            get {
                return ResourceManager.GetString("generalAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave dada no es correcta o no se corresponde con el dominio para el cual fue dada..
        /// </summary>
        internal static string G_GEO_BAD_KEY {
            get {
                return ResourceManager.GetString("G_GEO_BAD_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una consulta de una dirección no pudo ser correctamente analizada..
        /// </summary>
        internal static string G_GEO_BAD_REQUEST {
            get {
                return ResourceManager.GetString("G_GEO_BAD_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se especificó ningunha dirección..
        /// </summary>
        internal static string G_GEO_MISSING_QUERY {
            get {
                return ResourceManager.GetString("G_GEO_MISSING_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Una consulta de una dirección no pudo ser procesada correctamente..
        /// </summary>
        internal static string G_GEO_SERVER_ERROR {
            get {
                return ResourceManager.GetString("G_GEO_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo encontrar una correspondencia geográfica para una de las direcciones especificadas. Esto puede ser debido a que la dirección sea relativamente nueva o incorrecta..
        /// </summary>
        internal static string G_GEO_UNKNOWN_ADDRESS {
            get {
                return ResourceManager.GetString("G_GEO_UNKNOWN_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible calcular una ruta entre los puntos..
        /// </summary>
        internal static string G_GEO_UNKNOWN_DIRECTIONS {
            get {
                return ResourceManager.GetString("G_GEO_UNKNOWN_DIRECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico de mensajes.
        /// </summary>
        internal static string hMessages {
            get {
                return ResourceManager.GetString("hMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificador.
        /// </summary>
        internal static string identifier {
            get {
                return ResourceManager.GetString("identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última posición.
        /// </summary>
        internal static string lastPos {
            get {
                return ResourceManager.GetString("lastPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña incorrectos.
        /// </summary>
        internal static string lblLoginError {
            get {
                return ResourceManager.GetString("lblLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario o contraseña incorrectos.
        /// </summary>
        internal static string lblPasswordError {
            get {
                return ResourceManager.GetString("lblPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En este momento no es posible acceder a la aplicación. Por favor, inténtelo transcurridos unos minutos..
        /// </summary>
        internal static string lblUnknownError {
            get {
                return ResourceManager.GetString("lblUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En movimiento.
        /// </summary>
        internal static string moving {
            get {
                return ResourceManager.GetString("moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un activo.
        /// </summary>
        internal static string mustSelectActive {
            get {
                return ResourceManager.GetString("mustSelectActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una fecha.
        /// </summary>
        internal static string mustSelectDate {
            get {
                return ResourceManager.GetString("mustSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo asistido.
        /// </summary>
        internal static string newAssistBtn {
            get {
                return ResourceManager.GetString("newAssistBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva zona.
        /// </summary>
        internal static string newZone {
            get {
                return ResourceManager.GetString("newZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva zona.
        /// </summary>
        internal static string newZoneBtn {
            get {
                return ResourceManager.GetString("newZoneBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninguno.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede enviar el mensaje porque el dispositivo no se ha registrado para recibir notificaciones PUSH..
        /// </summary>
        internal static string NoPushDeviceToken {
            get {
                return ResourceManager.GetString("NoPushDeviceToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen eventos futuros.
        /// </summary>
        internal static string notExistEvent {
            get {
                return ResourceManager.GetString("notExistEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación no encontrada.
        /// </summary>
        internal static string notFindPlace {
            get {
                return ResourceManager.GetString("notFindPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detenido.
        /// </summary>
        internal static string parked {
            get {
                return ResourceManager.GetString("parked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono:.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string phone2 {
            get {
                return ResourceManager.GetString("phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programar evento.
        /// </summary>
        internal static string programmingEvents {
            get {
                return ResourceManager.GetString("programmingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de rellamadas.
        /// </summary>
        internal static string recallCount {
            get {
                return ResourceManager.GetString("recallCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo obligatorio.
        /// </summary>
        internal static string requiredField {
            get {
                return ResourceManager.GetString("requiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño de la imagen supera el máximo permitido (60x90).
        /// </summary>
        internal static string requiredFilterImage {
            get {
                return ResourceManager.GetString("requiredFilterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        internal static string returnBtn {
            get {
                return ResourceManager.GetString("returnBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string saveBtn {
            get {
                return ResourceManager.GetString("saveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos se han guardado correctamente.
        /// </summary>
        internal static string saveDataOk {
            get {
                return ResourceManager.GetString("saveDataOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar en el mapa.
        /// </summary>
        internal static string seeMap {
            get {
                return ResourceManager.GetString("seeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        internal static string sendBtn {
            get {
                return ResourceManager.GetString("sendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envíar mensaje.
        /// </summary>
        internal static string sendMsg {
            get {
                return ResourceManager.GetString("sendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El mensaje se ha enviado correctamente.
        /// </summary>
        internal static string sendMsgOk {
            get {
                return ResourceManager.GetString("sendMsgOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parado.
        /// </summary>
        internal static string stopped {
            get {
                return ResourceManager.GetString("stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        internal static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe añadir al menos 3 puntos a la zona.
        /// </summary>
        internal static string threePointsMap {
            get {
                return ResourceManager.GetString("threePointsMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconocido.
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos se han actualizado correctamente.
        /// </summary>
        internal static string updateDataOk {
            get {
                return ResourceManager.GetString("updateDataOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar perfil.
        /// </summary>
        internal static string updateProfile {
            get {
                return ResourceManager.GetString("updateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de usuario.
        /// </summary>
        internal static string userProfile {
            get {
                return ResourceManager.GetString("userProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver zonas.
        /// </summary>
        internal static string viewZones {
            get {
                return ResourceManager.GetString("viewZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to años.
        /// </summary>
        internal static string years {
            get {
                return ResourceManager.GetString("years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta de zona.
        /// </summary>
        internal static string zoneAlarm {
            get {
                return ResourceManager.GetString("zoneAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil de zona.
        /// </summary>
        internal static string zoneProfile {
            get {
                return ResourceManager.GetString("zoneProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zonas.
        /// </summary>
        internal static string zones {
            get {
                return ResourceManager.GetString("zones", resourceCulture);
            }
        }
    }
}
